---
- hosts: central
  tasks:
    - name: deploy central controller
      shell: bash /root/1_standalone-central.sh >> 1_standalone-central.log
      tags: controller
    - name: extract controller information for edge node deployment input
      shell: bash /root/2_create-compute-stack-env.sh >> 2_create-compute-stack-env.log
      tags: extract
    - name: download export_control_plane.tar.gz from central
      synchronize:
        mode: pull
        src: /root/export_control_plane.tar.gz
        dest: /tmp/export_control_plane.tar.gz
      tags: extract
- hosts: edge
  tasks:
    - name: upload export_control_plane.tar.gz to edge nodes
      synchronize:
        mode: push
        dest: /tmp/export_control_plane.tar.gz
        src: /tmp/export_control_plane.tar.gz
      tags: extract
    - name: unpack export_control_plane.tar.gz on edge nodes
      unarchive:
        dest: /root/
        src: /tmp/export_control_plane.tar.gz
      tags: extract
    - name: deploy edge nodes
      shell: bash /root/3_standalone-edge.sh >> 3_standalone-edge.log
      tags: edge
- hosts: central
  tasks:
    - name: discover nova compute nodes from central controller
      command: docker exec nova_api nova-manage cell_v2 discover_hosts --verbose
      become: true
      tags: disc
    - name: list hypervisors from central controller
      shell: "export OS_CLOUD=standalone; openstack hypervisor list -f value"
      tags: disc
    - name: test from central controller
      shell: bash /root/4_test.sh >> 4_test.log
      ignore_errors: true
      tags: test
    - name: list compute instances from central controller
      shell: "export OS_CLOUD=standalone; openstack server list -f value"
      ignore_errors: true
      tags: report
- hosts: edge
  tasks:
    - name: list virsh instances on edge nodes
      command: docker exec nova_libvirt virsh list
      register: virsh_list
      become: true
      tags: report
    - debug: msg="{{virsh_list.stdout}}"
